In [1]:
import pandas as pd
df = pd.read_csv('./datasets/game_sales.csv')

In [2]:
df.head()

,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,rating,date
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,76.0,51.0,8.0,324.0,E,2006-10-09
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,1985-01-20
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.80,3.79,3.29,35.57,82.0,73.0,8.3,712.0,E,2008-11-16
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,80.0,73.0,8.0,193.0,E,2009-11-25
4,Pokemon Red/Pokemon Blue,G,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,1996-08-17

In [3]:
# values = the column you want to summarize
# index = the column you want to groupby
# by default pivot table takes the mean value for each group

# Mean sales for each genre.
df.pivot_table(values="global_sales", index="genre")

              global_sales
genre
Action            0.503397
Adventure         0.163430
Fighting          0.519873
Misc              0.446347
Platform          0.924156
Puzzle            0.396358
Racing            0.571155
Role-Playing      0.614440
Shooter           0.791751
Simulation        0.425087
Sports            0.557121
Strategy          0.239401

In [4]:
# Sum of sales for each genre.
df.pivot_table(values="global_sales", index="genre", aggfunc=sum).sort_values(
    by="global_sales", ascending=False)

              global_sales
genre
Action             1761.89
Sports             1340.99
Shooter            1067.28
Role-Playing        949.31
Platform            831.74
Misc                808.78
Racing              731.65
Fighting            449.17
Simulation          392.78
Puzzle              243.76
Adventure           241.55
Strategy            175.72

In [5]:
import numpy as np

df.pivot_table(values="global_sales", index="genre", aggfunc=[np.mean, np.median, np.sum])

                     mean       median          sum
             global_sales global_sales global_sales
genre
Action           0.503397        0.180      1761.89
Adventure        0.163430        0.040       241.55
Fighting         0.519873        0.200       449.17
Misc             0.446347        0.150       808.78
Platform         0.924156        0.265       831.74
Puzzle           0.396358        0.090       243.76
Racing           0.571155        0.180       731.65
Role-Playing     0.614440        0.170       949.31
Shooter          0.791751        0.225      1067.28
Simulation       0.425087        0.140       392.78
Sports           0.557121        0.210      1340.99
Strategy         0.239401        0.090       175.72

In [6]:
# Get most frequent platforms
mf_platforms = df['platform'].value_counts(sort=True)[:10].index.tolist()
games_of_mfps = df[df['platform'].isin(mf_platforms)]

# Group by two variables.
games_of_mfps.pivot_table(values="global_sales", index="genre", columns="platform", aggfunc=sum)

platform,DS,GBA,PC,PS,PS2,PS3,PSP,Wii,X,X360
genre,,,,,,,,,,
Action,112.86,55.80,32.44,127.05,272.79,302.82,64.28,114.45,49.28,240.69
Adventure,46.19,14.70,10.34,20.98,21.45,22.50,11.15,17.88,3.07,15.20
Fighting,7.12,4.21,0.29,72.68,92.63,51.26,21.83,23.74,13.55,37.43
Misc,136.02,36.28,8.74,44.91,101.16,47.25,14.01,217.22,9.58,92.00
Platform,75.98,78.32,0.51,64.21,72.51,29.83,17.12,89.13,9.66,11.42
Puzzle,83.00,12.95,1.01,12.08,5.90,0.59,5.58,15.41,0.42,0.85
Racing,38.14,18.82,4.12,103.19,156.28,72.24,34.37,60.40,31.53,65.09
Role-Playing,124.60,64.21,48.28,78.30,93.50,73.99,49.17,13.73,13.51,71.46
Shooter,7.93,3.61,46.78,39.31,108.57,192.77,19.68,28.15,63.56,277.67
Simulation,130.59,5.93,53.46,25.33,42.68,10.46,6.29,36.08,7.11,14.15
Sports,31.48,16.44,12.26,120.98,273.44,134.75,41.62,288.91,54.30,139.41
Strategy,14.91,7.45,46.72,21.69,15.18,4.83,10.57,5.04,2.78,10.06

In [7]:
# NaN values may mean there is no that kind of the pair in the dataset,
# or pair may have NaN as its value. fill_value replaces them.

# margins=true, marginal last column and row will be added.
# the cells which values we filled in with zeros wont be included (for mean etc).

df.pivot_table(values="global_sales", index="genre", columns="platform",
               aggfunc=sum, fill_value=0, margins=True)

platform,2600,3DO,3DS,DC,DS,G,GBA,GC,GEN,GG,...,SCD,SNES,TG16,WS,Wii,WiiU,X,X360,XOne,All
genre,,,,,,,,,,,,,,,,,,,,,
Action,29.34,0.00,59.92,1.26,112.86,7.92,55.80,37.84,2.74,0.00,...,0.00,10.08,0.00,0.00,114.45,19.63,49.28,240.69,40.24,1761.89
Adventure,1.70,0.06,5.05,2.50,46.19,17.16,14.70,5.93,0.19,0.00,...,0.00,1.50,0.14,0.00,17.88,0.19,3.07,15.20,2.97,241.55
Fighting,1.24,0.00,10.67,1.83,7.12,0.00,4.21,18.43,5.90,0.00,...,0.00,26.95,0.00,0.00,23.74,6.45,13.55,37.43,2.55,449.17
Misc,3.58,0.00,11.67,0.00,136.02,13.35,36.28,16.73,0.03,0.00,...,0.10,5.02,0.00,0.00,217.22,13.13,9.58,92.00,8.42,808.78
Platform,13.27,0.00,34.29,2.54,75.98,54.91,78.32,28.66,15.45,0.04,...,1.50,65.65,0.00,0.00,89.13,22.18,9.66,11.42,1.02,831.74
Puzzle,14.68,0.02,5.67,0.00,83.00,47.47,12.95,4.70,0.00,0.00,...,0.00,6.38,0.00,0.00,15.41,1.39,0.42,0.85,0.00,243.76
Racing,2.91,0.00,15.33,2.65,38.14,4.55,18.82,21.90,0.26,0.00,...,0.07,13.49,0.00,0.00,60.40,8.03,31.53,65.09,10.68,731.65
Role-Playing,0.00,0.00,90.41,0.68,124.60,88.24,64.21,13.15,0.27,0.00,...,0.06,36.43,0.00,1.22,13.73,3.15,13.51,71.46,11.91,949.31
Shooter,26.48,0.00,1.30,0.33,7.93,1.20,3.61,13.65,0.13,0.00,...,0.00,6.07,0.02,0.00,28.15,6.10,63.56,277.67,65.77,1067.28
Simulation,0.45,0.02,28.17,0.52,130.59,3.55,5.93,8.59,0.00,0.00,...,0.00,5.63,0.00,0.00,36.08,0.20,7.11,14.15,0.77,392.78
Sports,3.43,0.00,6.27,3.66,31.48,9.05,16.44,25.53,3.20,0.00,...,0.00,17.87,0.00,0.00,288.91,3.23,54.30,139.41,29.01,1340.99
Strategy,0.00,0.00,2.19,0.00,14.91,8.05,7.45,4.32,0.19,0.00,...,0.14,4.98,0.00,0.21,5.04,1.25,2.78,10.06,0.48,175.72
All,97.08,0.10,270.94,15.97,808.82,255.45,318.72,199.43,28.36,0.04,...,1.87,200.05,0.16,1.43,910.14,84.93,258.35,975.43,173.82,8994.62

In [8]:
df.pivot_table(values="global_sales", index="genre", columns="platform",
               aggfunc=[np.mean, np.median, np.sum], fill_value=0, margins=True)

                  mean                                                    \
platform          2600       3DO       3DS        DC        DS         G
genre
Action        0.480984  0.000000  0.298109  0.420000  0.323381  1.320000
Adventure     0.850000  0.060000  0.126250  0.227273  0.176973  3.432000
Fighting      0.620000  0.000000  0.711333  0.152500  0.192432  0.000000
Misc          0.716000  0.000000  0.197797  0.000000  0.338358  1.668750
Platform      1.474444  0.000000  1.182414  1.270000  0.825870  2.890000
Puzzle        1.334545  0.020000  0.246522  0.000000  0.333333  3.164667
Racing        0.485000  0.000000  1.393636  0.441667  0.544857  2.275000
Role-Playing  0.000000  0.000000  0.993516  0.170000  0.596172  4.201905
Shooter       1.103333  0.000000  0.185714  0.110000  0.188810  1.200000
Simulation    0.450000  0.020000  0.880312  0.520000  0.429572  0.710000
Sports        0.285833  0.000000  0.232222  0.366000  0.205752  1.005556
Strategy      0.000000  0.000000  0.121667  0.000000  0.184074  1.150000
All           0.729925  0.033333  0.489946  0.307115  0.359635  2.606633

                                                  ...   sum                \
platform           GBA        GC       GEN    GG  ...   SCD    SNES  TG16
genre                                             ...
Action        0.326316  0.374653  0.913333  0.00  ...  0.00   10.08  0.00
Adventure     0.367500  0.296500  0.095000  0.00  ...  0.00    1.50  0.14
Fighting      0.183043  0.438810  1.180000  0.00  ...  0.00   26.95  0.00
Misc          0.321062  0.464722  0.030000  0.00  ...  0.10    5.02  0.00
Platform      0.543889  0.392603  2.207143  0.04  ...  1.50   65.65  0.00
Puzzle        0.294318  0.361538  0.000000  0.00  ...  0.00    6.38  0.00
Racing        0.285152  0.342187  0.260000  0.00  ...  0.07   13.49  0.00
Role-Playing  0.879589  0.487037  0.090000  0.00  ...  0.06   36.43  0.00
Shooter       0.088049  0.273000  0.130000  0.00  ...  0.00    6.07  0.02
Simulation    0.296500  0.715833  0.000000  0.00  ...  0.00    5.63  0.00
Sports        0.180659  0.223947  1.066667  0.00  ...  0.00   17.87  0.00
Strategy      0.413889  0.392727  0.190000  0.00  ...  0.14    4.98  0.00
All           0.377630  0.354227  1.050370  0.04  ...  1.87  200.05  0.16


platform        WS     Wii   WiiU       X    X360    XOne      All
genre
Action        0.00  114.45  19.63   49.28  240.69   40.24  1761.89
Adventure     0.00   17.88   0.19    3.07   15.20    2.97   241.55
Fighting      0.00   23.74   6.45   13.55   37.43    2.55   449.17
Misc          0.00  217.22  13.13    9.58   92.00    8.42   808.78
Platform      0.00   89.13  22.18    9.66   11.42    1.02   831.74
Puzzle        0.00   15.41   1.39    0.42    0.85    0.00   243.76
Racing        0.00   60.40   8.03   31.53   65.09   10.68   731.65
Role-Playing  1.22   13.73   3.15   13.51   71.46   11.91   949.31
Shooter       0.00   28.15   6.10   63.56  277.67   65.77  1067.28
Simulation    0.00   36.08   0.20    7.11   14.15    0.77   392.78
Sports        0.00  288.91   3.23   54.30  139.41   29.01  1340.99
Strategy      0.21    5.04   1.25    2.78   10.06    0.48   175.72
All           1.43  910.14  84.93  258.35  975.43  173.82  8994.62

[13 rows x 96 columns]